apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  # Ensures external access & load balancing
  selector:
    app: backend  # Targets backend pods
  ports:
    - protocol: TCP
      port: 80        # External port for traffic
      targetPort: 80  # Matches backend container port
