apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  type: LoadBalancer
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: keerthanar228/e-commerce-backend:latest
          ports:
            - containerPort: 80
